spring:
  mvc:
    static-path-pattern: /build/**
  resources:
    static-locations: classpath:/build/

server:
  port: 8443
  tomcat:
    uri-encoding: utf-8
  servlet:
    context-path: /
  ssl:
    key-store: keystore.p12
    key-store-password: Huawei@123
    key-store-type: PKCS12
    key-alias: tomcat